services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongodb/mongo_data:/data/db
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
    restart: unless-stopped
    networks:
      - chatapp-network

  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    container_name: service-registry
    ports:
      - "${SERVICE_REGISTRY_PORT}:8761"
    environment:
      SPRING_APPLICATION_NAME: service-registry
    networks:
      - chatapp-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${API_GATEWAY_PORT}:8762"
    depends_on:
      - service-registry
    networks:
      - chatapp-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-registry:8761/eureka/

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/${MONGO_DB_NAME}
    depends_on:
      - mongodb
      - service-registry
    restart: unless-stopped
    networks:
      - chatapp-network

volumes:
  mongo_data:

networks:
  chatapp-network:
    driver: bridge