services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongodb/mongo_data:/data/db
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
    restart: unless-stopped
    networks:
      - chatapp-network

  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    restart: unless-stopped
    networks:
      - chatapp-network

  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    container_name: service-registry
    ports:
      - "${SERVICE_REGISTRY_PORT}:8761"
    environment:
      SPRING_APPLICATION_NAME: service-registry
    networks:
      - chatapp-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${API_GATEWAY_PORT}:8762"
    depends_on:
      - service-registry
    networks:
      - chatapp-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-registry:8761/eureka/

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
#    expose:
#      - "${AUTH_SERVICE_PORT}"
    ports:
      - "${AUTH_SERVICE_PORT}:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/${MONGO_DB_NAME}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    depends_on:
      - mongodb
      - service-registry
    restart: unless-stopped
    networks:
      - chatapp-network

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    container_name: chat-service
#    expose:
#      - "${CHAT_SERVICE_PORT}"
    ports:
      - "${CHAT_SERVICE_PORT}:8083"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/${MONGO_DB_NAME}
    depends_on:
      - mongodb
      - service-registry
    restart: unless-stopped
    networks:
      - chatapp-network

  media-service:
    build:
      context: ./media-service
      dockerfile: Dockerfile
    container_name: media-service
    expose:
      - "8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8084
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: chat-media
    depends_on:
      - minio
      - service-registry
    restart: unless-stopped
    networks:
      - chatapp-network

networks:
  chatapp-network:
    driver: bridge